### PR TITLE
Add content_available to GCM notifications

### PR DESCRIPTION
**Pull request by aried3r**
Sorry for the two pull requests, now from the correct branch.

Adds `content_available` to GCM notifications. Read more about it [here](https://developers.google.com/cloud-messaging/ios/client#receive_messages_through_the_gcm_apns_interface)

### CODE REVIEW

**Comment by aried3r** [comment]
The tests that are failing are the same ones that fail in the master branch, shouldn't have anything to do with this branch.

**Comment by aried3r** [comment]
Hey @ileitch, do you want this in a 2.5.1 release or is 2.6.0 ok with you? So I can adapt the file and class names if necessary.

**Comment by victorlcampos** [comment]
Could You closed my PR? I think this is the right one.

**Comment by victorlcampos** [comment]
#204

**Comment by aried3r** [comment]
You can close your own PRs :)

**Pull request merged**
