### PR TITLE
Support APNS mutable-content

### PR DESCRIPTION
**Pull request by tdtran**
See Apple dev documentation https://developer.apple.com/reference/usernotifications/unnotificationserviceextension

I added a new AR migration `Rpush280Updates` assuming the next `rpush` version will be `2.8.0`.

### CODE REVIEW

**Comment by austenito** [comment]
Any word on when this will get merged?

**Comment by tdtran** [comment]
OK. I merged. We've been using this branch in production for a couple of months without any issues but it would be great if others give it a try too.

**Comment by aried3r** [comment]
Nice! Thanks!

It's weird that this didn't trigger a build in Travis. It doesn't even see the commit right now.

Would you be up to drafting a new release? Updating the changelog with everything [since 2.7.0](https://github.com/rpush/rpush/compare/v2.7.0...master) and pinging _ileitch_ to release it, once done? I can help!

I know it's a lot to ask, but I did it in the past a few times and I think it's nice that the community helps out :)

**Comment by tdtran** [comment]
Ha. I'll give it a try in the next couple of days.

**Comment by rvsingh** [comment]
Is mutable content support released in 2.7?

**Comment by aried3r** [comment]
No, it's only available in the `master` branch.

**Comment by rgalindo33** [comment]
@aried3r is it safe to use the v3.0.0.rc1 ? when are you planning on release v3.0.0? im waiting for this to make use of mutable content notificaitons

**Comment by aried3r** [comment]
3.0.0 is out :)

**Pull request merged**
