### PR TITLE
Update apns_http2.rb

### PR DESCRIPTION
**Pull request by mldoscar**
Fixed issue [ERROR] NoMethodError, undefined method `log_error' for #<Rpush::Daemon::Dispatcher::ApnsHttp2:0x0055ef9bf4fc78> thrown while rpush daemon started

### CODE REVIEW

**Comment by aried3r** [comment]
Hey @mldoscar! Thanks for your PR! It seems there's a rubocop issue, can you maybe look into it? :)

And could you try to add a test for this? That would be great!

**Comment by mldoscar** [comment]
> Hey @mldoscar! Thanks for your PR! It seems there's a rubocop issue, can you maybe look into it? :)
> 
> And could you try to add a test for this? That would be great!

The rubocop issue was fixed @aried3r. Could you guide me where to put the test into the existing spec structure?

**Comment by rsndates** [comment]
Im dealing with this issue as well

**Comment by rsndates** [comment]
Is there a way to be able to add these changes locally until this is approved for merge?

**Comment by mldoscar** [comment]
> Is there a way to be able to add these changes locally until this is approved for merge?

Meanwhile, can remove `gem 'rpush'` line and replace it with this on your gemfile:
```ruby
gem 'rpush', :git => 'https://github.com/mldoscar/rpush', :branch => 'master'
```

**Comment by rsndates** [comment]
> > Is there a way to be able to add these changes locally until this is approved for merge?
> 
> Meanwhile, can remove `gem 'rpush'` line and replace it with this on your gemfile:
> 
> ```ruby
> gem 'rpush', :git => 'https://github.com/mldoscar/rpush', :branch => 'master'
> ```

Oh okay. Thanks

**Comment by drn** [comment]
Hey @mldoscar - thanks for the PR!

You can add coverage here - https://github.com/rpush/rpush/blob/master/spec/functional/apns2_spec.rb. The current spec is currently just stubbing the client, which is why the `log_error` exception in the `on(:error)` block wasn't covered

**Comment by jhottenstein** [comment]
I'm adding more tests now.  I'll merge this now and add a test myself.

**Pull request merged**
