### PR TITLE
Basic Firefox support

### PR DESCRIPTION
**Pull request by evserykh**
https://github.com/rpush/rpush/issues/259

### CODE REVIEW

**Comment by aried3r** [comment]
Hey! Looking good, but could you add some tests? Have a look around in the specs to see how other services like GCM, APNS etc are tested. :)

**Comment by evserykh** [comment]
I'll do it later. Now don't have so much time

**Comment by evserykh** [comment]
Perhaps @planio-gmbh branch [https://github.com/planio-gmbh/rpush/commits/mozilla_push](https://github.com/planio-gmbh/rpush/commits/mozilla_push) looks more completed

**Comment by aried3r** [comment]
@evserykh, hey there! Are you still interested in this? I'm still open to having this in rpush, if there's at least some specs like for the other services. So far it seems, you're the only one interested in this, since nobody else has shown up (which is fine, maybe people don't yet know they want this!). But merging without tests will shift the maintenance burden on the rpush maintainers, which tests could at least alleviate a bit.

I hope you understand and I thank you for your contribution!

**Comment by evserykh** [comment]
hi man! hope you are doing well. I'll try doing it next week. ok?

**Comment by aried3r** [comment]
Hey! Does this PR https://github.com/rpush/rpush/pull/574 help you in any way with Firefox?

**Pull request closed without merging**
