### PR TITLE
Updated RSpec version

### PR DESCRIPTION
**Pull request by yihyang**
Fixed https://github.com/rpush/rpush/issues/529

Changes
- Updated rspec version

### CODE REVIEW

**Comment by aried3r** [comment]
Thanks for the PR! As you can see, sadly all Redis test runs don't work if RSpec is upgraded, sadly I don't know why exactly.

**Comment by yihyang** [comment]
I see, I think there are already some errors on the current versions. However upgrading the RSpec caused it to fail. GIve me sometime to have a look if you are ok.

Check the existing PR: https://travis-ci.org/rpush/rpush/jobs/590578647
There are some error messages that actually occurred but was not enough to cause it to fail

**Comment by aried3r** [comment]
That would be awesome, thank you!

**Review by benlangfeld — CHANGES_REQUESTED** [review]
Hi @yihyang , thanks for the contribution!

This includes a downgrade of Modis, which I don't think is desirable, and has some merge conflicts. Could you maybe resolve those two?

**Comment by aried3r** [comment]
@benlangfeld, just for a little background, I tried a few times updating RSpec, but always failed due to obscure failures that IMO should not have been caused by a switch from 3.4 to 3.5. At least I couldn't find anything in the changelog of rspec that would suggest so.

I didn't want to invest the time to maybe even git-bisect through v3.4.0 to v3.5.0, but with rspec 4 being a thing, I assume this might make maintenance easier along the way.

**Comment by aried3r** [comment]
I'm closing this but will reopen if there's new activity.

**Pull request closed without merging**
