### PR TITLE
Support Rails 7.2

### PR DESCRIPTION
**Pull request by benlangfeld**

### CODE REVIEW

**Comment by benlangfeld** [comment]
This is pending a release of 7.2.2 to include https://github.com/rails/rails/pull/52843.

**Comment by chaadow** [comment]
Hey @benlangfeld ! just to let you know Rails `7.2.2` has been released 🎉

**Comment by chaadow** [comment]
( Also  rails 8.0.0.rc2 is on `rubygems`,  which makes the Rails `8.0` imminent, it would be great if you can make the rails dependency more lenient 🙏🏼, especially for those like me who are on  `main` branch )
Thanks!

**Comment by benlangfeld** [comment]
> ( Also rails 8.0.0.rc2 is on `rubygems`, which makes the Rails `8.0` imminent, it would be great if you can make the rails dependency more lenient 🙏🏼, especially for those like me who are on `main` branch ) Thanks!

This change should allow you to use rails 8.0.0. A PR to test against it would be good too :)

**Comment by chaadow** [comment]
yes, I just saw the gemspec! any plans on releasing this? thanks!

**Comment by benlangfeld** [comment]
> yes, I just saw the gemspec! any plans on releasing this? thanks!

We need to do https://github.com/rpush/rpush/pull/713 first, and I'm not sure when I'll get time for that.

**Pull request merged**
