### PR TITLE
Allow disabling of APNS feedback for legacy apps.

### PR DESCRIPTION
**Pull request by drn**
Resolves https://github.com/rpush/rpush/issues/285

### CODE REVIEW

**Comment by drn** [comment]
Will debug, redis failures later tonight. Stay tuned!

**Comment by drn** [comment]
I've updated this PR to ensure redis support - this is ready for review now

**Comment by drn** [comment]
@aried3r This is rebased and ready for your feedback whenever you have time for it. Looks like the CI failures are already on master, so I believe that they are unrelated. Thanks!

**Comment by aried3r** [comment]
I'll only get to take a look at it next week. But until then a little nitpick, the changelog entry should go to the _Unreleased_ section of the file, I guess it happened due to the rebase and the intermittent release between this PR and rpush 4.1.0.

**Comment by drn** [comment]
Ah my fault, I didn't realize that `v4.1.0` was out already. Will adjust

EDIT: updated now!

**Pull request merged**
